import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

const source = await readFile(new URL("./template-page.tsx", import.meta.url), "utf8")

test("workflow detail loads agents through paged enterprise APIs", () => {
  assert.match(source, /fetchEnterpriseAIAgents\(\{ productScoped: 0, page: 1, limit: WORKFLOW_AGENT_OPTION_PAGE_SIZE \}\)/)
  assert.match(source, /fetchEnterpriseAIAgents\(\{ workflowId, page: 1, limit: WORKFLOW_ADOPTION_PAGE_SIZE \}\)/)
  assert.match(source, /fetchEnterpriseAIWorkflowAdoption\(\[workflowId\]\)/)
  assert.match(source, /loadAvailableAgentPage/)
  assert.match(source, /loadAdoptedAgentPage/)
  assert.match(source, /ListPagination/)
  assert.doesNotMatch(source, /fetchAIAgents/)
  assert.doesNotMatch(source, /limit:\s*1000/)
})

test("workflow detail uses adoption counts instead of current page length", () => {
  assert.match(source, /adoptionCount={adoptionCount}/)
  assert.match(source, /currentVersionAdoptionCount={currentVersionAdoptionCount}/)
  assert.match(source, /Math\.max\(0, adoptionCount - currentVersionAdoptionCount\)/)
  assert.match(source, /disabled={adoptionCount > 0 \|\| Boolean\(saving\)}/)
  assert.doesNotMatch(source, /adoptionCount={agents\.length}/)
  assert.doesNotMatch(source, /WorkflowReadiness definition={definition} stableVersionId={workflow\.currentStableVersionId} adoptionCount={agents\.length}/)
})

test("workflow detail renders the template before secondary modules finish", () => {
  assert.match(source, /const workflowData = await fetchEnterpriseAIWorkflow\(workflowId\)/)
  assert.match(source, /setWorkflow\(workflowData\)[\s\S]*setDefinition\(workflowData\.draftDefinition\)[\s\S]*setTemplateLoaded\(true\)[\s\S]*setLoading\(false\)[\s\S]*setVersionsLoading\(true\)/)
  assert.match(source, /const \[availableAgentsLoading, setAvailableAgentsLoading\] = useState\(false\)/)
  assert.match(source, /const \[blueprintTemplatesLoading, setBlueprintTemplatesLoading\] = useState\(false\)/)
  assert.match(source, /const versionsTask = fetchWorkflowVersionPage/)
  assert.match(source, /const availableAgentsTask = fetchEnterpriseAIAgents\(\{ productScoped: 0, page: 1, limit: WORKFLOW_AGENT_OPTION_PAGE_SIZE \}\)/)
  assert.match(source, /const adoptedAgentsTask = fetchEnterpriseAIAgents\(\{ workflowId, page: 1, limit: WORKFLOW_ADOPTION_PAGE_SIZE \}\)/)
  assert.match(source, /const blueprintTemplatesTask = fetchEnterpriseAIWorkflows\(\{ page: 1, limit: WORKFLOW_BLUEPRINT_TEMPLATE_PAGE_SIZE, scope: "platform" \}\)/)
  assert.match(source, /className="flex h-full min-h-0 flex-col overflow-hidden"/)
  assert.match(source, /label=\{wd\(t, "loading\.compose"\)\}/)
  assert.match(source, /label=\{wd\(t, "loading\.status"\)\}/)
  assert.match(source, /label=\{wd\(t, "blueprint\.loading"\)\}/)
  assert.doesNotMatch(source, /const \[workflowData, nodeSpecData, availableAgentPage, adoptedAgentPage, workflowPage, adoptionStatus\] = await Promise\.all/)
})

test("workflow detail avoids old explanatory copy", () => {
  assert.match(source, /const \[templateLoaded, setTemplateLoaded\] = useState\(false\)/)
  assert.match(source, /const \[adoptedAgentsLoaded, setAdoptedAgentsLoaded\] = useState\(false\)/)
  assert.match(source, /const initialLoading = loading && !templateLoaded/)
  assert.doesNotMatch(source, /if \(initialLoading\) \{\s*return/)
  assert.doesNotMatch(source, /if \(initialLoading\) return <EnterpriseWorkflowTemplateLoading \/>/)
  assert.match(source, /if \(initialLoading\) return <EnterpriseWorkflowTemplateLoading activeTab=\{activeTab\} onTabChange=\{setActiveTab\} \/>/)
  assert.match(source, /function WorkflowTemplateTabList\(\{ value, onChange \}/)
  assert.match(source, /<WorkflowTemplateTabList \/>/)
  assert.match(source, /function EnterpriseWorkflowTemplateLoading\(\{/)
  assert.match(source, /aria-busy="true" aria-label=\{wd\(t, "loading\.page"\)\}/)
  assert.match(source, /label=\{wd\(t, "loading\.status"\)\}/)
  assert.match(source, /label=\{wd\(t, "loading\.compose"\)\}/)
  assert.match(source, /label=\{wd\(t, "loading\.runs"\)\}/)
  assert.match(source, /label=\{wd\(t, "loading\.bindings"\)\}/)
  assert.match(source, /label=\{wd\(t, "loading\.versions"\)\}/)
  assert.match(source, /label=\{wd\(t, "loading\.adoption"\)\}/)
  assert.match(source, /RouteBreadcrumbs/)
  assert.match(source, /<RouteBreadcrumbs size="page" \/>/)
  assert.doesNotMatch(source, /<h1 className="text-xl font-semibold sm:text-2xl">\{workflow\.name\}<\/h1>/)
  assert.match(source, /initialLoading=\{adoptedAgentsLoading && !adoptedAgentsLoaded\}/)
  assert.doesNotMatch(source, /\(workflow === null \|\| definition === null\) && loading/)
  assert.doesNotMatch(source, /if \(loading\)\s*\{/)
  assert.doesNotMatch(source, /正在读取流程定义、版本和发布状态/)
  assert.doesNotMatch(source, /当前流程的全部产品机器人/)
  assert.doesNotMatch(source, /产品机器人|测试机器人|机器人配置|机器人发布版本/)
  assert.doesNotMatch(source, /BotIcon|SparklesIcon/)
  assert.doesNotMatch(source, /发布新版本不会影响任何线上客户/)
  assert.doesNotMatch(source, /版本升级不会自动影响线上服务/)
  assert.doesNotMatch(source, /线上服务不会自动切换/)
  assert.doesNotMatch(source, /当前没有生产 Release/)
  assert.doesNotMatch(source, /workflow\.description \|\| "暂无说明"/)
  assert.match(source, /workflow\.description\.trim\(\) \?/)
  assert.doesNotMatch(source, /DialogDescription/)
  assert.doesNotMatch(source, /SheetDescription/)
  assert.doesNotMatch(source, /workflow-preview-description/)
  assert.doesNotMatch(source, /客户从发起咨询到问题处理完成的主要阶段/)
  assert.doesNotMatch(source, /<p[^>]*>\{profile\.description\}<\/p>/)
  assert.doesNotMatch(source, /\{presentation\.description\}/)
  assert.doesNotMatch(source, /\{stage\.description\}/)
  assert.doesNotMatch(source, /\{capability\.description\}/)
  assert.doesNotMatch(source, /可在图谱与清单间切换查看/)
  assert.doesNotMatch(source, /spec\?\.description \|\| node\.type/)
  assert.doesNotMatch(source, /\{check\.description\}/)
  assert.doesNotMatch(source, /\{scenario\.description\}/)
  assert.doesNotMatch(source, /试运行专用/)
  assert.doesNotMatch(source, /关键路径自动生成/)
  assert.doesNotMatch(source, /不写真实工单或人工队列/)
  assert.doesNotMatch(source, /验证转人工链路/)
  assert.doesNotMatch(source, /测试输入不会进入人工队列/)
  assert.doesNotMatch(source, /不读写真实设备数据/)
  assert.doesNotMatch(source, /服务节点和条件将替换为平台标准方案/)
  assert.doesNotMatch(source, /只更新待发布配置/)
  assert.doesNotMatch(source, /历史版本和产品配置不变/)
  assert.doesNotMatch(source, /归档后模板不再出现在企业模板库中/)
  assert.doesNotMatch(source, /从入口到结束/)
  assert.doesNotMatch(source, /选择客户服务方案/)
  assert.doesNotMatch(source, /客户处理路径/)
  assert.doesNotMatch(source, /服务能力与边界/)
  assert.doesNotMatch(source, /标准问题回答|不识别设备上下文|全程不转人工/)
  assert.doesNotMatch(source, /有设备完整诊断|无设备基础服务/)
  assert.doesNotMatch(source, /识别设备与企业策略|满足条件时转人工/)
  assert.doesNotMatch(source, /只读版本，可试运行/)
  assert.doesNotMatch(source, /查看客户会话实际经过的节点/)
  assert.doesNotMatch(source, /按工作流自动筛选/)
  assert.doesNotMatch(source, /自定义流程节点/)
  assert.doesNotMatch(source, /结束本次流程执行/)
  assert.doesNotMatch(source, /runtimeVariableDescription/)
  assert.doesNotMatch(source, /<TableHead className="min-w-64">用途<\/TableHead>/)
  assert.doesNotMatch(source, /仅本次执行，草稿和线上版本不变/)
  assert.doesNotMatch(source, /关闭后，执行会停在第一个人工确认节点/)
  assert.doesNotMatch(source, /业务写入隔离/)
  assert.doesNotMatch(source, /完成后标记到画布/)
  assert.doesNotMatch(source, /运行结果按节点顺序展开/)
  assert.match(source, /wd\(t, "testPanel\.isolation"\)/)
  assert.match(source, /wd\(t, "testPanel\.emptyResult"\)/)
})
